### ISSUE TITLE
icon requests. 😄

### ISSUE THREAD

**Issue by piuvas** [Delta-Icons/linux#12]
retroarch: retroarch
lutris: lutris
heroic games launcher: heroic

retroarch is already there for android so...

**Comment by Disaster2life** [comment]
I could add the retroarch icon probably in a few hours, lutris I assume doesn't already have an existing icon, I'll see if I can draw it / something similar, same goes for heroic.

Feel free if you wish to make and contribute yourself!

**Comment by hausofwong** [comment]
@Disaster2life I already have a Heroic and Lutris icon. I'll try and get my icons uploaded tonight.

**Comment by Disaster2life** [comment]
Great! I forgot to go through the icons yesterday, if you could ping me on the discord when you open your PR, I'll add the retroarch icon to your branch, so it'll be merged at once

**Comment by Disaster2life** [comment]
Oh, yeah forgot about this, @derspyy all the icons have been merged, you should update to the latest release that should have been auto generated
