### ISSUE TITLE
new obsidian icon on Delta-Icons/android.

### ISSUE THREAD

**Issue by piuvas** [Delta-Icons/linux#16]
the linux icon should probably be updated to match the new android one.

also, i gotta ask: are all the repos going to be updated separately? since ios and windows are both planned, a more automated approach would be suitable. is there any interest in that?

**Comment by Disaster2life** [comment]
I'll update the obsidian logo from the android branch and open a pull request;

For the repo management, I am not involved in it, but from what I've observed I don't think there is any proper way to manage all three given how each of the repos have their own difficulties and how apps usually don't sync all three at the same time, would be interesting, if you want to get involved most of the other contributions are available on the discord.
