### ISSUE TITLE
Not working with KDE Plasma

### ISSUE THREAD

**Issue by amanullahmenjli** [Delta-Icons/linux#2]
i copied the delta folder to .icons in home folder but nothing appears in settings

**Comment by leifniem** [comment]
@creepertron95 do you have a KDE install at hand?

**Comment by maxtron95** [comment]
@amenallahmenjli Try testing in `.local/share/icons` to see if they appear there.

**Comment by maxtron95** [comment]
@leifniem I have XFCE installed mainly (I don't have KDE atm.) but I can get a KDE VM fired up soon.

**Comment by leifniem** [comment]
> @leifniem I have XFCE installed mainly (I don't have KDE atm.) but I can get a KDE VM fired up soon.

Let's see if we can get this fixed without it, otherwise i can offer to help out :)

**Comment by maxtron95** [comment]
@leifniem After looking at other icon themes, I realized that GTK and KDE distros both had different local directories for storing icons. I went ahead and updated the Readme to avoid confusion.

**Comment by amanullahmenjli** [comment]
thanks it works now but a lot of icons aren't available

**Comment by maxtron95** [comment]
@amenallahmenjli Glad to hear that the theme works now, Yes, not many icons are available at the moment, Feel free to request any missing icons here. Seeing as the original issue is solved, I'll close it out as completed.
