### ISSUE TITLE
Terminal Icon update

### ISSUE THREAD

**Issue by piuvas** [Delta-Icons/linux#20]
icon name: kitty

original:
![image](https://github.com/Delta-Icons/linux/assets/65043391/fc88d67f-fd3f-4c99-b6c6-d95bbb9c2721)

maybe an alt for the [whiskers](https://github.com/samholmes/whiskers) icon?
![image](https://github.com/Delta-Icons/linux/assets/65043391/1825c930-97be-443f-a980-14e7868c5e47)

**Comment by Disaster2life** [comment]
Left this open cause no artistic skills, but now I look at it, I think we can just do with like one terminal icon maybe? We do have two other terminal icons we could fall back on, but yeah, if someone wants to do custom icons, I am artistically incapable.
![image of three distinct terminal icons](https://github.com/Delta-Icons/linux/assets/19931889/edda1810-affd-4bfe-98bd-a8a093b3b355)

**Comment by piuvas** [comment]
those are nice : )

**Comment by Disaster2life** [comment]
interestingly? seems we don't use any of those, I assume we forked and used one of those, and then it got updated, We could switch to one of those for all the terminal icons, any preferences? Might also put it up for poll in the discord

**Comment by piuvas** [comment]
i liked the first one

**Comment by Disaster2life** [comment]
So far, it's 1 each for the left ``material-terminal.svg`` and right ``terminal.svg``, I think given most people are using termux on their phones? For consistency, it might be better to change to the right one, though I like how the left one looks

**Comment by Disaster2life** [comment]
Its been a few month, I think for consistencies sake, I'll update it over to ``terminal.svg`` and close this

**Comment by Disaster2life** [comment]
Did not take me 6 months to get around to this :-/ but yes, I decided on ``terminal.svg`` for consistency, someday hopefully we can make it easier to choose alternative icons for your personal preference, currently it shouldn't be that hard to change it to what you would personally prefer
