### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by MalteKiefer** [Delta-Icons/linux#3]
Hi,

I need these icons:

- [x] Teamviewer
- [x] Dino (https://dino.im/)
- [x] Flatseal (https://github.com/tchx84/Flatseal)
- [x] Gnome Contacts
- [x] PHPStorm
- [x] Gnome Terminal
- [x] Gnome Boxes

**Comment by leifniem** [comment]
Hi Malte,

we usually do not do requests, since we're a small team made up of volunteers, but we're happy to assist if you want to create these yourself :)

Feel free to refer to CONTRIBUTING.md and join the discord for any guidance.

**Comment by maxtron95** [comment]
However, It would probably be helpful to edit this to paste the `Icon=` line from the .desktop files of each requested program so it would be easier for me to do.

**Comment by MalteKiefer** [comment]
thanks so much for your work
