### ISSUE TITLE
Ubuntu 22.04.3 LTS Custom Desktop Environment Variable

### ISSUE THREAD

**Issue by KasimiraEike** [Delta-Icons/linux#30]
I get this running Ubuntu 22.04.3 LTS. Do you know what to do?

![Ubuntu](https://github.com/Delta-Icons/linux/assets/154630817/40e655fd-f1d6-4fbc-9a72-3999d64b358c)

**Comment by Disaster2life** [comment]
It seems Ubuntu has a custom desktop variable, I will write a patch by this evening hopefully, for now you should use the GTK path (option 1), and that should work.

**Comment by Disaster2life** [comment]
Added support via #31, could you run the script once more to see if it works now?

**Comment by KasimiraEike** [comment]
> Added support via #31, could you run the script once more to see if it works now?

No, the same error message came up again.
Using option 1 manually worked fine.

**Comment by Disaster2life** [comment]
That seems weird, does it throw any specific erorr messages or does it not work? I might have to spin up an ubuntu virtual machine to test maybe, at least the manual GTK method works, workaround for now, hopefully I can work on this soon.

**Comment by Disaster2life** [comment]
Fixed this with this [commit](https://github.com/Delta-Icons/linux/commit/47bc9e03c2906d8f2ca9fc8fd5aa96fd84fb7351), I tested it and it seemed to work, so I will close it now.

**Comment by KasimiraEike** [comment]
> Fixed this with this [commit](https://github.com/Delta-Icons/linux/commit/47bc9e03c2906d8f2ca9fc8fd5aa96fd84fb7351), I tested it and it seemed to work, so I will close it now.

Yes, your fix is successful. 👍
