### ISSUE TITLE
Unwanted space in install script

### ISSUE THREAD

**Issue by Disaster2life** [Delta-Icons/linux#33]
I just noticed that the install script adds a random space after it is run, visual bug, I am sure there is just some random line causing this, but I am opening this to get around to this at some point because it annoys the hell out of me.

![image](https://github.com/Delta-Icons/linux/assets/19931889/4443824d-89f6-4888-aff3-7c8c91c834d0)

**Comment by flameshikari** [comment]
This is caused by [that command](https://github.com/Delta-Icons/linux/blob/afdd096c13f58228958b5e139c67ea1ebcce1d26/install.sh#L40C9-L40C46). Removing the trailing space should fix it.

**Comment by Disaster2life** [comment]
that seems … super obvious, didnt spot it, thanks flame! Ill incorporate it in when I get time

**Comment by Disaster2life** [comment]
thanks flame, removed it now ``2595d21``
