### ISSUE TITLE
Several icon requests

### ISSUE THREAD

**Issue by kflpk** [Delta-Icons/linux#38]
Hello, I love your icon pack, howered I noticed it lacks some of desktop-only application icons, it seems most of the icons are for mobile devices.

Anyway here are the programs
- MATLAB
```desktop
Icon=matlab
```
- Thunderbird
```desktop
Icon=thunderbird
```

And some programs have icons but don't have links named after their flatpak version, those I noticed being
Signal with `Icon=org.signal.Signal`
MS Teams with `Icon=com.microsoft.Teams`

There are probably some I missed but that's what noticed.

**Comment by Disaster2life** [comment]
Heya! I am happy to hear other people also enjoy the icons, but sadly, the linux branch is an adaption of the android branch, that explains the lack of desktop only applications, I am not really skilled enough to do the icons myself (I have tried) and we don't have anyone making them specifically for the linux branch. I can't offer your options for Matlab and Thunderbird, though for the latter I have considered using a generic mail icon, and there might a thunderbird icon soon enough when K9 mail merged into thunderbird.

But yes many flatpak version are different from their local install variants, if you come across any missing flatpak ones feel free to ask for them to be added, they are easy to link, and I will add them now.

**Comment by Disaster2life** [comment]
Added the [links](https://github.com/Delta-Icons/linux/commit/6dc040e3972918eb3a7760a03a05a67bc083b9d3)

**Comment by kflpk** [comment]
I'm kinda confused. You said you aren't skilled enough to make the icons. So what is your process for creating the icons for the android version?

**Comment by Disaster2life** [comment]
I really only _maintain_ the linux branch, the android branch is maintained and developed by other people, and it also receives many more contributions from people who can art.

**Comment by kflpk** [comment]
Oh, okay. Do you think I can talk to some of the android contributors for a possible request, or should I just not bother them?

**Comment by Disaster2life** [comment]
You can ask them, they are usually available on the Discord if you wish to join that or ask them personally, I dont remember ever asking them for specific icons for the linux branch at least.
